# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "Ferris sweep"
product_name = "Ferris sweep"
vendor_id = 0xc2ab
product_id = 0x3939
manufacturer = "DPB"
chip = "rp2040"

[behavior.combo]
timeout = "150ms"
combos = [
  # Press J and K keys simultaneously to output Escape key
  { actions = ["J", "K"], output = "Escape" }
]

[layout]
rows = 4
cols = 10
layers = 8
keymap = [
    [
        ["Q"        , "W"        , "E"           , "R"          , "T",
         "Y"        , "U"        , "I"           , "O"          , "P",],

         ["MT(A,LShift)", "LT(5,S)"  , "LT(1,D)"     , "LT(3,F)"    , "G",
         "H"        , "LT(4,J)"  , "LT(2,K)"     , "LT(6,L)"    , "MT(Semicolon,RShift)",],

         ["Z"        , "MT(X,LCtrl )", "MT(C,LAlt)"   , "V"          , "B",
         "N"        , "M"        , "MT(Comma,RAlt)", "MT(Dot,RCtrl)", "Slash",],

         ["Kc0"       , "Backspace",
         "LT(7,SPC)", "Kc1"]
    ],
    [
        ["_"     , "_"     , "_"        , "_"       , "_",
         "_"     , "MouseBtn1"     , "MouseWheelUp"        , "MouseBtn2"       , "_",],

         ["_"     , "MouseBtn2"     , "NO"          , "MouseBtn1"       , "_",
         "_"     , "MouseLeft"     , "MouseDown"        , "MouseUp"       , "MouseR",],

         ["_"     , "_"     , "_"        , "_"       , "_",
         "_"     , "MouseWheelLeft"     , "MouseWheelDown"        , "MouseWheelRight"       , "_",],

         ["_"     , "_",
         "_"     , "_"]
    ],
    [
        ["_"     , "_"     , "PageUp"        , "_"       , "_",
         "_"     , "_"     , "_"        , "_"       , "_",],

         ["Left"     , "Up"       , "Down"        , "Right"       , "_",
         "_"     , "LGui"     , "NO"          , "MT(RAlt, RCtrl)" , "MT(RShift, RCtrl)",],

         ["_"     , "Home"     , "PageDown"        , "End"        , "_",
         "_"     , "_"     , "_"        , "_"       , "_",],

         ["_"     , "_",
         "_"     , "_"]
    ],
    [
        ["_"     , "_"     , "_"        , "_"       , "_",
         "_"     , "Underscore"     , "Shift(Backslash)"        , "Quote"       , "_",],

         ["Shift(Kc2)"     , "Shift(Kc8) "     , "Shift(Kc7)"        , "NO"         , "_",
         "Shift(Kc3)"     , "Shift(Grave)"     , "Slash"        , "Shift(Quote)"       , "Shift(Kc4)",],

         ["_"     , "_"     , "_"        , "_"       , "_",
         "_"     , "Minus"     , "Backslash"        , "Grave"        , "_",],

         ["MediaPrevTrack"    , "_",
         "_"     , "MediaNextTrack"],
    ],
    [
        ["_"     , "Shift(Semicolon)"     , "Shift(Comma)"          , "Shift(Dot)"         , "Semicolon",
         "_"     , "_"     , "_"        , "_"       , "_",],

         ["LeftBracket"     , "RightBracket"     , "Shift(Kc9)"        , "Shift(Kc0)"       , "AT",
         "_"     , "NO"       , "Shift(Plus)"         , "Plus"       , "Shift(Kc5)",],

         ["_"     , "Shift(Kc1)"     , "Shift(LeftBracket)"        , "Shift(RightBracket)"       , "_",
         "_"     , "_"     , "_"        , "_"       , "_",],

         ["KbVolumeDown"     , "_",
         "_"     , "KbVolumeUp"]
    ],
    [
        ["_"     , "_"     , "_"        , "_"       , "_",
         "_"     , "F7"       , "F8"          , "F9"         , "F10",],

         ["_"     , "NO"       , "MT(LAlt, LCtrl)"  , "_"       , "_",
         "_"     , "F4"       , "F5"          , "F6"         , "F11",],

         ["_"     , "_"     , "_"        , "_"       , "_",
         "_"     , "F1"       , "F2"          , "F3"         , "F12",],

         ["_"     , "_",
         "_"     , "_"]
    ],
    [
        ["KpSlash"     , "7"        , "8"           , "9"          , "KpPlus",
         "_"     , "_"     , "_"        , "_"       , "_",],

         ["0"        , "1"        , "2"           , "3"          , "KpMinus",
         "_"     , "_"     , "_"        , "NO"         , "_",],

         ["KpAsterisk"     , "4"        , "5"           , "6"          , "KpEnter",
         "_"     , "_"     , "_"        , "_"       , "_",],

         ["_"     , "_",
         "_"     , "_"]
    ],
    [
        ["_"     , "_"     , "Shift(Semicolon)"        , "Escape"        , "_",
         "_"     , "_"     , "_"        , "_"       , "Delete",],

         ["_"     , "Shift(Kc5)"     , "Slash"        , "Enter"        , "_",
         "DF(1)"       , "LGui"     , "_"        , "_"       , "_",],

        ["_"     , "_"     , "_"        , "Shift(Kc1)"       , "_",
         "DF(0)"       , "_"     , "MT(Comma, RAlt)", "MT(Dot, RCtrl)", "Bootloader",],

         ["_"     , "Tab",
         "NO"       , "_"]
    ],
]

[behavior]
tap_hold = { enable_hrm = true, prior_idle_time = "120ms", hold_timeout = "250ms", post_wait_time = "50ms"}

[split]
connection = "serial"

# we are defining the left side to be our primary.
[split.central]
rows = 4
cols = 5
row_offset = 0
col_offset = 0
serial = [{ instance = "PIO0", tx_pin = "PIN_1", rx_pin = "PIN_1" }]
[split.central.matrix]
matrix_type = "direct_pin"
direct_pins=[
    ["PIN_7", "PIN_26", "PIN_27", "PIN_28", "PIN_29", ],
    ["PIN_22", "PIN_20", "PIN_23", "PIN_21", "PIN_0", ],
    ["PIN_2", "PIN_3", "PIN_4", "PIN_5", "PIN_6", ],
    ["_", "_", "_", "PIN_8", "PIN_9", ],
]

[[split.peripheral]]
rows = 4
cols = 5
row_offset = 0
col_offset = 5
serial = [{ instance = "PIO0", tx_pin = "PIN_1", rx_pin = "PIN_1" }]
[split.peripheral.matrix]
matrix_type = "direct_pin"
direct_pins=[
    ["PIN_29", "PIN_28", "PIN_27", "PIN_26", "PIN_7", ],
    ["PIN_0", "PIN_21", "PIN_23", "PIN_20", "PIN_22", ],
    ["PIN_6", "PIN_5", "PIN_4", "PIN_3", "PIN_2", ],
    ["PIN_9", "PIN_8", "_", "_", "_", ],
]
