# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "Ferris sweep"
product_name = "Ferris sweep"
vendor_id = 0xc2ab
product_id = 0x3939
manufacturer = "DPB"
chip = "rp2040"

[behavior.combo]
timeout = "150ms"
combos = [
  # Press J and K keys simultaneously to output Escape key
  { actions = ["J", "K"], output = "Escape" }
]

[layout]
rows = 4
cols = 3
layers = 2
keymap = [
    [
        ["A", "B", "C"],
        ["Kc1", "Kc2", "Kc3"],
        ["LCtrl", "MO(1)", "LShift"],
        ["OSL(1)", "LT(2, Kc9)", "LM(1, LShift | LGui)"]
    ],
    [
        ["_", "TT(1)", "TG(2)"],
        ["_", "_", "_"],
        ["_", "_", "_"],
        ["_", "_", "_"]
    ],
]

[behavior]
tap_hold = { enable_hrm = true, prior_idle_time = "120ms", hold_timeout = "250ms", post_wait_time = "50ms"}

[split]
connection = "serial"

# we are defining the left side to be our primary.
[split.central]
rows = 2
cols = 2
row_offset = 0
col_offset = 0
serial = [{ instance = "PIO0", tx_pin = "PIN_1", rx_pin = "PIN_1" }]
[split.central.matrix]
matrix_type = "direct_pin"
direct_pins=[
    ["PIN_7", "PIN_26", "PIN_27", "PIN_28", "PIN_29", ],
    ["PIN_22", "PIN_20", "PIN_23", "PIN_21", "PIN_0", ],
    ["PIN_2", "PIN_3", "PIN_4", "PIN_5", "PIN_6", ],
    ["_", "_", "_", "PIN_8", "PIN_9", ],
]

[[split.peripheral]]
rows = 2
cols = 1
row_offset = 2
col_offset = 2
serial = [{ instance = "PIO0", tx_pin = "PIN_1", rx_pin = "PIN_1" }]
[split.peripheral.matrix]
matrix_type = "direct_pin"
direct_pins=[
    ["PIN_29", "PIN_28", "PIN_27", "PIN_26", "PIN_7", ],
    ["PIN_0", "PIN_21", "PIN_23", "PIN_20", "PIN_22", ],
    ["PIN_6", "PIN_5", "PIN_4", "PIN_3", "PIN_2", ],
    ["PIN_9", "PIN_8", "_", "_", "_", ],
]
