name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: cargo-bins/cargo-binstall@main
    - uses: actions/checkout@v4
    - name: Install rmkit, flip-link and cargo-make
      run: cargo binstall cargo-make -y

    - name: Build firmware
      working-directory: ./rmk
      run: cargo build --release

    - name: Build uf2 firmware
      working-directory: ./rmk
      run: cargo make uf2 --release

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: firmware_uf2
        path: rmk/*.uf2